### ISSUE TITLE
Not compiling on Ubuntu

### ISSUE THREAD

**Issue by rookboom** [trolleyman/ale-rs#1]
Hi, 

I am having a hard time getting this project to compile.
I'm stuck on this error when trying to run the example:
```
          /usr/bin/ld: NullDev.cxx:(.text.startup._GLOBAL__sub_I_NullDev.cxx+0x17): undefined reference to `std::ios_base::Init::~Init()'
          /usr/bin/ld: /home/johan/repos/ale-rs/target/release/deps/libale_sys-574dabc17e7e623d.rlib(NullDev.cxx.o):(.data.rel.ro._ZTI10NullDevice[_ZTI10NullDevice]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
          collect2: error: ld returned 1 exit status
```
It seems to be a linking problem. From what I read on StackOverflow, the solution is to add a flag 

-lstdc++ 

to the  g++ commandline. Do you have some environement variable that takes care of this?
I am able to build the *ale* submodule, but it seems to have trouble linking with the rust wrapper
when running
``` 
cargo run --release --example breakout
```

I should mention: 

```
cargo build
```

works, but 

```
cargo build --examples
```
does not.

Thanks
Johan

**Comment by trolleyman** [comment]
Hey! Thanks for kicking the tires around a bit. Yep, looks like on Ubuntu it isn't working.

I've got a fix here: #3 Can you confirm that it works?

**Comment by rookboom** [comment]
Yup, that works. Thanks!

**Comment by trolleyman** [comment]
No problem, any other issues just let me know :)
